# make a program executable

# Fortran Compiler
FC = ifort

# compiler options
FOPT = -module -g -03 

# other objects outside main.f90
# OBJECTS = none atm 

#outputdata.exe : outputdata.f90
#	$(FC) outputdata.f90 $(FOPT) -o outputdata.exe

nudat.exe : nudat.f90
	$(FC) nudat.f90 $(FOPT) -o nudat.exe
